spring.application.name=flexible-schedule

# DATABASE
#USING EnvFile plugin and .env file for environment variables
spring.datasource.username= ${DB_USERNAME}
spring.datasource.password= ${DB_PASSWORD}

spring.datasource.url= ${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver



# If building a REST API (which I plan to do in this app)
# disable this to avoid:
#   lazy-loading issues at the controller or serialization layer.
#
#By default, it's set to TRUE, which means:
#    You can lazily fetch related entities (e.g., user.getRoles())
#    even after your service layer has returned.
#
#    This can accidentally cause extra database queries during response serialization
#    especially in REST APIs where you're returning entities as JSON.
spring.jpa.open-in-view=false